--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 시퀀스
--------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP SEQUENCE SEQ_MEMBER_NO; -- MEMBER 회원
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE; -- MEMBER 회원
DROP SEQUENCE SEQ_CATEGORY_NO; -- CATEGORY 카테고리
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE; -- CATEGORY 카테고리
DROP SEQUENCE SEQ_AD_MEMBER_NO; -- AD_MEMBER 관리자
CREATE SEQUENCE SEQ_AD_MEMBER_NO NOCACHE NOCYCLE; -- AD_MEMBER 관리자
DROP SEQUENCE SEQ_SETTLEMENT_INFO_NO; -- SETTLEMENT_INFO 정산정보
CREATE SEQUENCE SEQ_SETTLEMENT_INFO_NO NOCACHE NOCYCLE; -- SETTLEMENT_INFO 정산정보
DROP SEQUENCE SEQ_PROJECT_EDIT_HISTORY_NO; -- PROJECT_EDIT_HISTORY 프로젝트 수정 이력
CREATE SEQUENCE SEQ_PROJECT_EDIT_HISTORY_NO NOCACHE NOCYCLE; -- PROJECT_EDIT_HISTORY 프로젝트 수정 이력

DROP SEQUENCE SEQ_PAYMENT_NO; -- PAYMENT 결제정보
CREATE SEQUENCE SEQ_PAYMENT_NO NOCACHE NOCYCLE; -- PAYMENT 결제정보
DROP SEQUENCE SEQ_PAYMENT_TYPE_NO; -- PAYMENT_TYPE 결제수단
CREATE SEQUENCE SEQ_PAYMENT_TYPE_NO NOCACHE NOCYCLE; -- PAYMENT_TYPE 결제수단
DROP SEQUENCE SEQ_PAYMENT_STATUS_NO; -- PAYMENT_STATUS 결제상태
CREATE SEQUENCE SEQ_PAYMENT_STATUS_NO NOCACHE NOCYCLE; -- PAYMENT_STATUS 결제상태
DROP SEQUENCE SEQ_REVIEW_NO; -- REVIEW 후기
CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE NOCYCLE; -- REVIEW 후기
DROP SEQUENCE SEQ_BACKER_NO; -- BACKER 후원정보
CREATE SEQUENCE SEQ_BACKER_NO NOCACHE NOCYCLE; -- BACKER 후원정보

DROP SEQUENCE SEQ_PROJECT_NO; -- PROJECT 프로젝트
CREATE SEQUENCE SEQ_PROJECT_NO NOCACHE NOCYCLE; -- BACKER 후원정보
DROP SEQUENCE SEQ_REWARD_NO; -- REWARD 선물
CREATE SEQUENCE SEQ_REWARD_NO NOCACHE NOCYCLE; -- REWARD 선물
DROP SEQUENCE SEQ_PROJECT_STATUS_NO; -- PROJECT_STATUS 프로젝트상태
CREATE SEQUENCE SEQ_PROJECT_STATUS_NO NOCACHE NOCYCLE; -- PROJECT_STATUS 프로젝트상태
DROP SEQUENCE SEQ_PROJECT_UPDATE_NO; -- PROJECT_UPDATE 업데이트
CREATE SEQUENCE SEQ_PROJECT_UPDATE_NO NOCACHE NOCYCLE; -- PROJECT_UPDATE 업데이트
DROP SEQUENCE SEQ_COMMUNITY_NO; -- PROJECT_UPDATE 커뮤니티
CREATE SEQUENCE SEQ_COMMUNITY_NO NOCACHE NOCYCLE; -- PROJECT_UPDATE 커뮤니티


--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 테이블
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- MEMBER(회원) 테이블
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
	NO	                NUMBER	            PRIMARY KEY
	, NAME	            VARCHAR2(42)	    NOT NULL
	, EMAIL	            VARCHAR2(150)	    NOT NULL        UNIQUE
	, PWD	            VARCHAR2(50)	    NOT NULL
	, PIC	            VARCHAR2(500)	    NULL
	, INTRO	            VARCHAR2(2500)	    NULL
	, SITE_URL	        VARCHAR2(500)	    NULL
	, ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE
	, UPDATE_DATE	    TIMESTAMP	        NULL
	, QUIT_YN	        CHAR(1)	            DEFAULT 'N' CHECK( QUIT_YN IN ('Y','N') )
);
COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.NAME IS '회원 이름 기본/변경가능';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일(아이디)';
COMMENT ON COLUMN MEMBER.PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.PIC IS '회원 프로필사진';
COMMENT ON COLUMN MEMBER.INTRO IS '회원 소개';
COMMENT ON COLUMN MEMBER.SITE_URL IS '회원 웹사이트';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일자';
COMMENT ON COLUMN MEMBER.UPDATE_DATE IS '회원 정보 수정일자';
COMMENT ON COLUMN MEMBER.QUIT_YN IS '회원 탈퇴 여부';

-- CATEGORY(카테고리) 테이블
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY (
	NO	                    NUMBER		        NOT NULL PRIMARY KEY
	, MAIN_CATEGORY_NO	    NUMBER		        NOT NULL
	, SUB_CATEGORY_NO	    NUMBER		        NOT NULL
	, MAIN_CATEGORY	        VARCHAR2(100)		NOT NULL
	, SUB_CATEGORY	        VARCHAR2(100)		NOT NULL
);
COMMENT ON COLUMN CATEGORY.NO IS '카테고리 번호';
COMMENT ON COLUMN CATEGORY.MAIN_CATEGORY_NO IS '대분류 번호';
COMMENT ON COLUMN CATEGORY.SUB_CATEGORY_NO IS '소분류 번호';
COMMENT ON COLUMN CATEGORY.MAIN_CATEGORY IS '대분류 이름';
COMMENT ON COLUMN CATEGORY.SUB_CATEGORY IS '소분류 이름';

-- AD_MEMBER(관리자) 테이블
DROP TABLE AD_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE AD_MEMBER (
	NO	                NUMBER		        NOT NULL PRIMARY KEY
	, ID	            VARCHAR2(60)		NOT NULL
	, NAME	            VARCHAR2(42)		NOT NULL
	, PWD	            VARCHAR2(30)		NOT NULL
	, PIC	            VARCHAR2(500)		NULL
	, ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE	NOT NULL
	, QUIT_YN	        CHAR(1)	            DEFAULT 'N'	CHECK( QUIT_YN IN ('Y','N') )
);
COMMENT ON COLUMN AD_MEMBER.NO IS '관리자 번호';
COMMENT ON COLUMN AD_MEMBER.ID IS '관리자 계정 아이디';
COMMENT ON COLUMN AD_MEMBER.NAME IS '관리자 이름';
COMMENT ON COLUMN AD_MEMBER.PWD IS '관리자 비밀번호';
COMMENT ON COLUMN AD_MEMBER.PIC IS '관리자 프로필사진';
COMMENT ON COLUMN AD_MEMBER.ENROLL_DATE IS '계정생성일자';
COMMENT ON COLUMN AD_MEMBER.QUIT_YN IS '계정 활성화 여부';

-- REWARD(선물) 테이블
DROP TABLE REWARD CASCADE CONSTRAINTS;
CREATE TABLE REWARD(
    NO              NUMBER          PRIMARY KEY NOT NULL
    , PROJECT_NO    NUMBER          NOT NULL
    , AMOUNT        NUMBER          NOT NULL
    , NAME          VARCHAR2(1000)   NOT NULL
);
COMMENT ON COLUMN REWARD.NO IS '선물 번호';
COMMENT ON COLUMN REWARD.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN REWARD.AMOUNT IS '선물 금액';
COMMENT ON COLUMN REWARD.NAME IS '선물 이름';

-- PROJECT(프로젝트) 테이블
DROP TABLE PROJECT CASCADE CONSTRAINTS;
CREATE TABLE PROJECT(
    NO                  NUMBER          PRIMARY KEY NOT NULL
    , STATUS_NO         NUMBER          DEFAULT 1
    , CATEGORY_NO       NUMBER          NULL
    , MEMBER_NO         NUMBER          NOT NULL
    , TITLE             VARCHAR2(150)   NULL
    , GOAL_AMOUNT       NUMBER          NULL
    , IMAGE_URL         VARCHAR2(150)   NULL
    , TXT_DESCRIPTION   VARCHAR2(4000)  NULL
    , TXT_BUDGET        VARCHAR2(4000)  NULL
    , TXT_SCHEDULE      VARCHAR2(4000)  NULL
    , TXT_TEAM          VARCHAR2(4000)  NULL
    , TXT_ITEM          VARCHAR2(4000)  NULL
    , CURRENT_AMOUNT    NUMBER          DEFAULT 0
    , OK_YN             CHAR(1)         DEFAULT 'N' CHECK(OK_YN IN('Y' , 'N'))
    , OK_DATE           TIMESTAMP       NULL
    , ENROLL_DATE       TIMESTAMP       NULL
    , START_DATE        TIMESTAMP       NULL
    , END_DATE          TIMESTAMP       NULL
    , CAL_DATE          TIMESTAMP       NULL
    , DELETE_YN         CHAR(1)         DEFAULT 'N' CHECK(DELETE_YN IN('Y', 'N'))
);
COMMENT ON COLUMN PROJECT.NO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT.STATUS_NO IS '프로젝트 상태 번호';
COMMENT ON COLUMN PROJECT.CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN PROJECT.MEMBER_NO IS '창작자 번호';
COMMENT ON COLUMN PROJECT.TITLE IS '프로젝트 제목';
COMMENT ON COLUMN PROJECT.GOAL_AMOUNT IS '프로젝트 목표 금액';
COMMENT ON COLUMN PROJECT.IMAGE_URL IS '프로젝트 대표 이미지';
COMMENT ON COLUMN PROJECT.TXT_DESCRIPTION IS '프로젝트 소개';
COMMENT ON COLUMN PROJECT.TXT_BUDGET IS '프로젝트 예산 소개';
COMMENT ON COLUMN PROJECT.TXT_SCHEDULE IS '프로젝트 일정 소개';
COMMENT ON COLUMN PROJECT.TXT_TEAM IS '프로젝트 팀 소개';
COMMENT ON COLUMN PROJECT.TXT_ITEM IS '프로젝트 선물 소개';
COMMENT ON COLUMN PROJECT.CURRENT_AMOUNT IS '현재 모인 금액';
COMMENT ON COLUMN PROJECT.OK_YN IS '프로젝트 승인 여부';
COMMENT ON COLUMN PROJECT.OK_DATE IS '프로젝트 승인 날짜';
COMMENT ON COLUMN PROJECT.ENROLL_DATE IS '프로젝트 등록날짜';
COMMENT ON COLUMN PROJECT.START_DATE IS '프로젝트 시작일';
COMMENT ON COLUMN PROJECT.END_DATE IS '프로젝트 종료일';
COMMENT ON COLUMN PROJECT.CAL_DATE IS '프로젝트 정산일';
COMMENT ON COLUMN PROJECT.DELETE_YN IS '프로젝트 삭제 여부';

-- PROJECT_STATUS(프로젝트 상태) 테이블
DROP SEQUENCE SEQ_PROJECT_STATUS_NO;
CREATE SEQUENCE SEQ_PROJECT_STATUS_NO NOCACHE NOCYCLE;

DROP TABLE PROJECT_STATUS CASCADE CONSTRAINTS;
CREATE TABLE PROJECT_STATUS(
    NO          NUMBER          PRIMARY KEY NOT NULL
    , STATUS    VARCHAR2(10)    NOT NULL
);
COMMENT ON COLUMN PROJECT_STATUS.NO IS '프로젝트 상태 번호';
COMMENT ON COLUMN PROJECT_STATUS.STATUS IS '프로젝트 상태';

-- PROJECT_UPDATE(업데이트) 테이블
DROP TABLE PROJECT_UPDATE CASCADE CONSTRAINTS;
CREATE TABLE PROJECT_UPDATE(
    NO              NUMBER          PRIMARY KEY NOT NULL
    , PROJECT_NO    NUMBER          NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);
COMMENT ON COLUMN PROJECT_UPDATE.NO IS '업데이트 번호';
COMMENT ON COLUMN PROJECT_UPDATE.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT_UPDATE.CONTENT IS '업데이트 내용';
COMMENT ON COLUMN PROJECT_UPDATE.ENROLL_DATE IS '업데이트 내용 등록일';

-- COMMUNITY(커뮤니티) 테이블
DROP TABLE COMMUNITY CASCADE CONSTRAINTS;
CREATE TABLE COMMUNITY(
    NO                          NUMBER              PRIMARY KEY NOT NULL
    , PROJECT_NO                NUMBER              NOT NULL
    , MEMBER_NO                 NUMBER              NOT NULL
    , CONTENT                   VARCHAR2(4000)      NOT NULL
    , CONTENT_ENROLL_DATE       TIMESTAMP           DEFAULT SYSDATE
    , REPLY                     VARCHAR2(4000)      NULL
    , REPLY_ENROLL_DATE         TIMESTAMP           NULL
);
COMMENT ON COLUMN COMMUNITY.NO IS '커뮤니티 번호';
COMMENT ON COLUMN COMMUNITY.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN COMMUNITY.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN COMMUNITY.CONTENT IS '내용';
COMMENT ON COLUMN COMMUNITY.CONTENT_ENROLL_DATE IS '내용 등록일';
COMMENT ON COLUMN COMMUNITY.REPLY IS '답변';
COMMENT ON COLUMN COMMUNITY.REPLY_ENROLL_DATE IS '답변 등록일';

-- SETTLEMENT_INFO(정산정보) 테이블 외래키있음
DROP TABLE SETTLEMENT_INFO CASCADE CONSTRAINTS;
CREATE TABLE SETTLEMENT_INFO (
	NO	                NUMBER		        NOT NULL PRIMARY KEY
	, PROJECT_NO	    NUMBER		        NOT NULL
	, BANK_NAME	        VARCHAR2(50)		NULL
	, NAME	            VARCHAR2(50)		NULL
	, ACCOUNT_NUM	    NUMBER		        NULL
);
COMMENT ON COLUMN SETTLEMENT_INFO.NO IS '정산정보 번호';
COMMENT ON COLUMN SETTLEMENT_INFO.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN SETTLEMENT_INFO.BANK_NAME IS '거래은행 이름';
COMMENT ON COLUMN SETTLEMENT_INFO.NAME IS '예금주명';
COMMENT ON COLUMN SETTLEMENT_INFO.ACCOUNT_NUM IS '계좌번호';

-- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블
DROP TABLE PROJECT_EDIT_HISTORY CASCADE CONSTRAINTS;
CREATE TABLE PROJECT_EDIT_HISTORY (
	NO	                NUMBER          NOT NULL PRIMARY KEY
	, PROJECT_NO	    NUMBER		    NOT NULL
	, MEMBER_NO     	NUMBER		    NOT NULL
	, MODIFY_DATE	    TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN PROJECT_EDIT_HISTORY.NO IS '수정이력 번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.MODIFY_DATE IS '프로젝트 수정 이력';

-- REVIEW(후기) 테이블
DROP TABLE REVIEW CASCADE CONSTRAINTS;
CREATE TABLE REVIEW(
    NO                  NUMBER              NOT NULL PRIMARY KEY
    , MEMBER_NO         NUMBER              NOT NULL
    , PROJECT_NO        NUMBER              NOT NULL
    , BACKER_NO         NUMBER              NOT NULL
    , CONTENT           VARCHAR2(4000)      NOT NULL
    , IMAGE             VARCHAR2(4000)      NULL
    , RATING            NUMBER              NOT NULL
);
COMMENT ON COLUMN REVIEW.NO IS '후기 번호';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN REVIEW.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN REVIEW.BACKER_NO IS '후원 번호';
COMMENT ON COLUMN REVIEW.CONTENT IS '후기 내용';
COMMENT ON COLUMN REVIEW.IMAGE IS '후기 이미지';
COMMENT ON COLUMN REVIEW.RATING IS '후기 별점';

-- BACKER(후원정보) 테이블
DROP TABLE BACKER CASCADE CONSTRAINTS;
CREATE TABLE BACKER(
    NO                  NUMBER          NOT NULL PRIMARY KEY
    , PROJECT_NO        NUMBER          NOT NULL
    , MEMBER_NO         NUMBER          NOT NULL
    , REWARD_NO         NUMBER          NOT NULL
    , BACKING_DATE      TIMESTAMP       DEFAULT SYSDATE NOT NULL
    , RETRACT_YN        CHAR(1)         DEFAULT 'N' NOT NULL
);
COMMENT ON COLUMN BACKER.NO IS '후원자 번호';
COMMENT ON COLUMN BACKER.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN BACKER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN BACKER.REWARD_NO IS '선물 번호';
COMMENT ON COLUMN BACKER.BACKING_DATE IS '후원일자';
COMMENT ON COLUMN BACKER.RETRACT_YN IS '후원취소 여부';

-- PAYMENT_STATUS(결제상태) 테이블
DROP TABLE PAYMENT_STATUS CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_STATUS (
    NO                  NUMBER          NOT NULL PRIMARY KEY
    , PAYMENT_STATUS    VARCHAR2(20)    NOT NULL
);
COMMENT ON COLUMN PAYMENT_STATUS.NO IS '결제상태 번호';
COMMENT ON COLUMN PAYMENT_STATUS.PAYMENT_STATUS IS '결제상태';

-- PAYMENT_TYPE(결제수단) 테이블
DROP TABLE PAYMENT_TYPE CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_TYPE (
    NO                  NUMBER          NOT NULL PRIMARY KEY
    , PAYMENT_TYPE      VARCHAR2(100)   NOT NULL
);
COMMENT ON COLUMN PAYMENT_TYPE.NO IS '결제수단 번호';
COMMENT ON COLUMN PAYMENT_TYPE.PAYMENT_TYPE IS '결제수단';

-- PAYMENT(결제정보) 테이블
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT (
    NO                      NUMBER          NOT NULL PRIMARY KEY
    , BACKER_NO             NUMBER          NOT NULL
    , PROJECT_NO            NUMBER          NOT NULL
    , PAYMENT_TYPE_NO       NUMBER          NOT NULL
    , PAYMENT_STATUS_NO     NUMBER          NOT NULL
    , PAYMENT_DATE          TIMESTAMP       NOT NULL
    , AMOUNT                NUMBER          NOT NULL
);
COMMENT ON COLUMN PAYMENT.NO IS '결제정보 번호';
COMMENT ON COLUMN PAYMENT.BACKER_NO IS '후원자 번호';
COMMENT ON COLUMN PAYMENT.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_TYPE_NO IS '결제수단 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS_NO IS '결제상태 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제 일자';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제 금액';

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 외래키
--------------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE SETTLEMENT_INFO ADD CONSTRAINT PROJECT_NO FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- SETTLEMENT_INFO(정산정보) 테이블 외래키
ALTER TABLE PROJECT_EDIT_HISTORY ADD CONSTRAINT FK_HISTORY_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 외래키
ALTER TABLE PROJECT_EDIT_HISTORY ADD CONSTRAINT FK_HISTORY_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO); -- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 외래키
ALTER TABLE BACKER ADD CONSTRAINT FK_BACKER_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- BACKER(후원정보) 테이블 외래키
ALTER TABLE BACKER ADD CONSTRAINT FK_BACKER_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO); -- BACKER(후원정보) 테이블 외래키
ALTER TABLE BACKER ADD CONSTRAINT FK_BACKER_REWARD FOREIGN KEY(REWARD_NO) REFERENCES REWARD(NO); -- BACKER(후원정보) 테이블 외래키
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_BACKER FOREIGN KEY(BACKER_NO) REFERENCES BACKER(NO); -- PAYMENT(결제정보) 테이블 외래키
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- PAYMENT(결제정보) 테이블 외래키
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_PAYMENT_TYPE FOREIGN KEY(PAYMENT_TYPE_NO) REFERENCES PAYMENT_TYPE(NO); -- PAYMENT(결제정보) 테이블 외래키
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAYMENT_PAYMENT_STATUS FOREIGN KEY(PAYMENT_STATUS_NO) REFERENCES PAYMENT_STATUS(NO); -- PAYMENT(결제정보) 테이블 외래키
ALTER TABLE REVIEW ADD CONSTRAINT FK_REVIEW_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO); -- REVIEW(후기) 테이블 외래키
ALTER TABLE REVIEW ADD CONSTRAINT FK_REVIEW_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- REVIEW(후기) 테이블 외래키
ALTER TABLE REVIEW ADD CONSTRAINT FK_REVIEW_BACKER FOREIGN KEY(BACKER_NO) REFERENCES BACKER(NO);  -- REVIEW(후기) 테이블 외래키
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);  -- PROJECT(프로젝트) 테이블 외래키
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO);  -- PROJECT(프로젝트) 테이블 외래키
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_PROJECT_STATUS FOREIGN KEY(STATUS_NO) REFERENCES PROJECT_STATUS(NO);  -- PROJECT(프로젝트) 테이블 외래키
ALTER TABLE REWARD ADD CONSTRAINT FK_REWARD_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO);  -- REWARD(선물) 테이블 외래키
ALTER TABLE PROJECT_UPDATE ADD CONSTRAINT FK_PROJECT_UPDATE_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO);  -- PROJECT_UPDATE(업데이트) 테이블 외래키
ALTER TABLE COMMUNITY ADD CONSTRAINT FK_COMMUNITY_PROJECT FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO);  -- COMMUNITY(커뮤니티) 테이블 외래키
ALTER TABLE COMMUNITY ADD CONSTRAINT FK_COMMUNITY_MEMBER FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO);  -- COMMUNITY(커뮤니티) 테이블 외래키

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 더미데이터
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- MEMBER(회원) 테이블 더미 데이터
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '현지연', 'clsrnclsrn1111@naver.com', '1234', 'image.jpg', '향수 애호가를 위한 프래그런스 브랜드. 세이리.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '한윤지', 'gksdbswl@gmail.com', '1234', 'image.jpg', '창작자분들을 위한 유니크한 자료를 만듭니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '이경민', 'dlrudals@naver.com', '1234', 'image.jpg', '<지난 펀딩 소재 스토어 - 오픈중>', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '판타지문학사', 'fantasy@naver.com', '1234', 'image.jpg', '판타지 세계의 모든 것들을 다루고 있습니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'TextPlanet', 'textplanet@gmail.com', '1234', 'image.jpg', 'TextPlanet(텍스트플래닛)은 창작자를 위한 새로운 세계를 언어를 통해 창조하는 언어학 창작 그룹입니다. 높은 완성도로 여러분께 만족감을 드리겠습니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '나랑하', 'narangha@naver.com', '1234', 'image.jpg', '우리 주변의 다양한 이야기를 소개하는 출판 전문 스튜디오, 스튜디오 나랑하입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '나래꿈', 'nareggoum@naver.com', '1234', 'image.jpg', '트위터 : @naredream 인스타 : naredream', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '하이꽈베트남어', 'betnam@gmail.com', '1234', 'image.jpg', '<도전! 베트남 요리왕>을 통해 다 함께 베트남의 매력 속에 빠져 보세요!', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '위콘 게임즈 (WeCon Games)', 'wecon@naver.com', '1234', 'image.jpg', '안녕하세요! 보드게임 작가 도지 입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '야생의 멧씨', 'metcy@naver.com', '1234', 'image.jpg', '솔직한 즐거움으로 보드게임을 만들고 있는 멧씨입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
commit;

-- AD_MEMBER(관리자) 테이블 더미 데이터
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin1', '관리자1', '1234', 'admin_pic1.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin2', '관리자2', '1234', 'admin_pic2.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin3', '관리자3', '1234', 'admin_pic3.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin4', '관리자4', '1234', 'admin_pic4.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin5', '관리자5', '1234', 'admin_pic5.jpg', SYSDATE, 'N');
commit;

-- CATEGORY(카테고리) 테이블 더미 데이터
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 1, '비디오게임', 'RPG');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 2, '비디오게임', '시뮬레이션');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 3, '비디오게임', '생존');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 4, '비디오게임', '추리·공포');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 5, '비디오게임', '리듬');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 6, '비디오게임', '기타');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 1, '모바일게임', '퍼즐');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 2, '모바일게임', '슈팅');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 3, '모바일게임', '시뮬레이션');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 4, '모바일게임', '어드벤처');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 5, '모바일게임', '타이쿤');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 6, '모바일게임', '기타');
COMMIT;

-- PROJECT_STATUS(프로젝트 상태) 테이블 더미 데이터
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '작성중');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '심사중');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '승인됨');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '반려됨');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '진행중');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '성공');
INSERT INTO PROJECT_STATUS(NO, STATUS) VALUES (SEQ_PROJECT_STATUS_NO.NEXTVAL, '실패');
COMMIT;

-- PROJECT(프로젝트) 테이블 더미 데이터
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 11, 1, '몽글몽글 도깨비 키우기 게임 <차깨비 찻집>', 1000000, '차깨비 찻집 대표이미지', '차깨비 찻집 소개', '차깨비 찻집 예산', '차깨비 찻집 일정 소개', '차깨비 찻집 팀 소개', '차깨비 찻집 선물 소개', 3846000, 'Y', TO_DATE('2023.10.04','YYYY.MM.DD'), TO_DATE('2023.10.03','YYYY.MM.DD'), TO_DATE('2023.10.05','YYYY.MM.DD'), TO_DATE('2023.12.04','YYYY.MM.DD'), TO_DATE('2023.12.05','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 10, 2, '달 뒤편의 꾸덕한 비밀, 게임 <치즈문>', 2500000, '치즈문 대표이미지', '치즈문 소개', '치즈문 예산', '치즈문 일정 소개', '치즈문 팀 소개', '치즈문 선물 소개', 7650000, 'Y', TO_DATE('2023.10.06','YYYY.MM.DD'), TO_DATE('2023.10.05','YYYY.MM.DD'), TO_DATE('2023.10.09','YYYY.MM.DD'), TO_DATE('2023.11.24','YYYY.MM.DD'), TO_DATE('2023.11.25','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 2, 4, '목장에서 동물과 힐링하는 시간 <니나노: 푸른 목장>', 3000000, '니나노 대표이미지', '니나노 소개', '니나노 예산', '니나노 일정 소개', '니나노 팀 소개', '니나노 선물 소개', 4236000, 'Y', TO_DATE('2023.10.11','YYYY.MM.DD'), TO_DATE('2023.10.09','YYYY.MM.DD'), TO_DATE('2023.10.12','YYYY.MM.DD'), TO_DATE('2023.11.20','YYYY.MM.DD'), TO_DATE('2023.11.21','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 11, 5, '신비한 조류 마을의 멋진 요리사가 되어보자! <새동산>', 500000, '새동산 대표이미지', '새동산 소개', '새동산 예산', '새동산 일정 소개', '새동산 팀 소개', '새동산 선물 소개', 1315000, 'Y', TO_DATE('2023.10.20','YYYY.MM.DD'), TO_DATE('2023.10.18','YYYY.MM.DD'), TO_DATE('2023.10.21','YYYY.MM.DD'), TO_DATE('2023.12.01','YYYY.MM.DD'), TO_DATE('2023.12.02','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 1, 6, '아름다운 스토리의 감동 RPG 게임! 트레이시아 스토리!', 200000, '트레이시아 대표이미지', '트레이시아 소개', '트레이시아 예산', '트레이시아 일정 소개', '트레이시아 팀 소개', '트레이시아 선물 소개', 599000, 'Y', TO_DATE('2023.10.23','YYYY.MM.DD'), TO_DATE('2023.10.22','YYYY.MM.DD'), TO_DATE('2023.10.25','YYYY.MM.DD'), TO_DATE('2023.11.30','YYYY.MM.DD'), TO_DATE('2023.12.01','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 9, 3, '궁중 암투, 동양 육성 시뮬레이션 <새로운 왕을 위하여>', 800000, '새로운 왕을 위하여 대표이미지', '새로운 왕을 위하여 소개', '새로운 왕을 위하여 예산', '새로운 왕을 위하여 일정 소개', '새로운 왕을 위하여 팀 소개', '새로운 왕을 위하여 선물 소개', 2566600, 'Y', TO_DATE('2023.10.31','YYYY.MM.DD'), TO_DATE('2023.10.30','YYYY.MM.DD'), TO_DATE('2023.11.01','YYYY.MM.DD'), TO_DATE('2023.12.15','YYYY.MM.DD'), TO_DATE('2023.12.16','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 7, 12, 8, '성실하고 싹싹한 집사 구합니다! <냥냥섬: 전설의 집사>', 1500000, '냥냥섬 대표이미지', '냥냥섬 소개', '냥냥섬 예산', '냥냥섬 일정 소개', '냥냥섬 팀 소개', '냥냥섬 선물 소개', 1280000, 'Y', TO_DATE('2023.11.05','YYYY.MM.DD'), TO_DATE('2023.11.03','YYYY.MM.DD'), TO_DATE('2023.11.06','YYYY.MM.DD'), TO_DATE('2023.11.29','YYYY.MM.DD'), TO_DATE('2023.11.30','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 4, 3, 7, '오컬트 생존 추리 어드벤처 노베나 디아볼로스', 5000000, '노베나 디아볼로스 대표이미지', '노베나 디아볼로스 소개', '노베나 디아볼로스 예산', '노베나 디아볼로스 일정 소개', '노베나 디아볼로스 팀 소개', '노베나 디아볼로스 선물 소개', 0, 'N', TO_DATE('2023.11.07','YYYY.MM.DD'), TO_DATE('2023.11.05','YYYY.MM.DD'), TO_DATE('2023.11.08','YYYY.MM.DD'), TO_DATE('2023.12.18','YYYY.MM.DD'), TO_DATE('2023.12.19','YYYY.MM.DD'), 'Y');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 7, 6, 9, 'Full Metal Furies', 8000000, 'Full Metal Furies 대표이미지', 'Full Metal Furies 소개', 'Full Metal Furies 예산', 'Full Metal Furies 일정 소개', 'Full Metal Furies 팀 소개', 'Full Metal Furies 선물 소개', 7895000, 'Y', TO_DATE('2023.11.10','YYYY.MM.DD'), TO_DATE('2023.11.08','YYYY.MM.DD'), TO_DATE('2023.11.11','YYYY.MM.DD'), TO_DATE('2023.12.29','YYYY.MM.DD'), TO_DATE('2023.12.30','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 12, 10, '리듬게임 프로젝트 : KALPA', 1500000, 'KALPA 대표이미지', 'KALPA 소개', 'KALPA 예산', 'KALPA 일정 소개', 'KALPA 팀 소개', 'KALPA 선물 소개', 1680000, 'Y', TO_DATE('2023.11.15','YYYY.MM.DD'), TO_DATE('2023.11.14','YYYY.MM.DD'), TO_DATE('2023.11.16','YYYY.MM.DD'), TO_DATE('2024.01.15','YYYY.MM.DD'), TO_DATE('2024.01.16','YYYY.MM.DD'), 'N');

INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 4, 1, '연결된 단서들을 따라 사건을 추리하라 <커넥티드 클루>', 2300000, '커넥티드 클루 대표이미지', '커넥티드 클루 소개', '커넥티드 클루 예산', '커넥티드 클루 일정 소개', '커넥티드 클루 팀 소개', '커넥티드 클루 선물 소개', 3426000, 'Y', TO_DATE('2023.11.20','YYYY.MM.DD'), TO_DATE('2023.11.19','YYYY.MM.DD'), TO_DATE('2023.11.22','YYYY.MM.DD'), TO_DATE('2024.01.07','YYYY.MM.DD'), TO_DATE('2024.01.08','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 6, 5, 4, 'URLATE, 웹에서 즐기는 리듬게임', 1750000, 'URLATE 대표이미지', 'URLATE 소개', 'URLATE 예산', 'URLATE 일정 소개', 'URLATE 팀 소개', 'URLATE 선물 소개', 2024000, 'Y', TO_DATE('2023.11.26','YYYY.MM.DD'), TO_DATE('2023.11.25','YYYY.MM.DD'), TO_DATE('2023.11.27','YYYY.MM.DD'), TO_DATE('2024.01.23','YYYY.MM.DD'), TO_DATE('2024.01.24','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 5, 3, 2, '60 Seconds! Reatomized', 1300000, '60 Seconds 대표이미지', '60 Seconds 소개', '60 Seconds 예산', '60 Seconds 일정 소개', '60 Seconds 팀 소개', '60 Seconds 선물 소개', 1560000, 'Y', TO_DATE('2023.12.01','YYYY.MM.DD'), TO_DATE('2023.11.29','YYYY.MM.DD'), TO_DATE('2023.12.02','YYYY.MM.DD'), TO_DATE('2024.02.05','YYYY.MM.DD'), TO_DATE('2024.02.06','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 5, 7, 3, '세상에 단 하나뿐인 나만의 환상 도감 <별의 여행자 라라>', 2000000, '별의 여행자 라라 대표이미지', '별의 여행자 라라 소개', '별의 여행자 라라 예산', '별의 여행자 라라 일정 소개', '별의 여행자 라라 팀 소개', '별의 여행자 라라 선물 소개', 1800000, 'Y', TO_DATE('2023.12.09','YYYY.MM.DD'), TO_DATE('2023.12.08','YYYY.MM.DD'), TO_DATE('2023.12.10','YYYY.MM.DD'), TO_DATE('2024.02.09','YYYY.MM.DD'), TO_DATE('2024.02.10','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 5, 2, 5, 'Banished', 2600000, 'Banished 대표이미지', 'Banished 소개', 'Banished 예산', 'Banished 일정 소개', 'Banished 팀 소개', 'Banished 선물 소개', 2584000, 'Y', TO_DATE('2023.12.16','YYYY.MM.DD'), TO_DATE('2023.12.15','YYYY.MM.DD'), TO_DATE('2023.12.18','YYYY.MM.DD'), TO_DATE('2024.03.02','YYYY.MM.DD'), TO_DATE('2024.03.03','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 5, 2, 6, 'Princess Maker 3: Fairy Tales Come True', 1800000, 'Princess Maker 3 대표이미지', 'Princess Maker 3 소개', 'Princess Maker 3 예산', 'Princess Maker 3 일정 소개', 'Princess Maker 3 팀 소개', 'Princess Maker 3 선물 소개', 1984000, 'Y', TO_DATE('2023.12.24','YYYY.MM.DD'), TO_DATE('2023.12.22','YYYY.MM.DD'), TO_DATE('2023.12.25','YYYY.MM.DD'), TO_DATE('2024.02.18','YYYY.MM.DD'), TO_DATE('2024.02.19','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 5, 4, 7, '미스터리 공포게임 <연결고리> 파트1 목각인형의 저주', 500000, '연결고리 대표이미지', '연결고리 소개', '연결고리 예산', '연결고리 일정 소개', '연결고리 팀 소개', '연결고리 선물 소개', 708000, 'Y', TO_DATE('2024.01.03','YYYY.MM.DD'), TO_DATE('2024.01.01','YYYY.MM.DD'), TO_DATE('2024.01.04','YYYY.MM.DD'), TO_DATE('2024.02.24','YYYY.MM.DD'), TO_DATE('2024.02.25','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, OK_DATE, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 3, 12, 8, '체감형 모바일 리듬액션 게임 OverRapid', 1200000, 'OverRapid 대표이미지', 'OverRapid 소개', 'OverRapid 예산', 'OverRapid 일정 소개', 'OverRapid 팀 소개', 'OverRapid 선물 소개', 0, 'Y', TO_DATE('2024.01.28','YYYY.MM.DD'), TO_DATE('2024.01.27','YYYY.MM.DD'), TO_DATE('2024.02.05','YYYY.MM.DD'), TO_DATE('2024.04.02','YYYY.MM.DD'), TO_DATE('2024.04.03','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 2, 8, 9, '내가 움직이는대로 캐릭터가 움직이는 모바일 FPS 컴퍼니맨', 5000000, '컴퍼니맨 대표이미지', '컴퍼니맨 소개', '컴퍼니맨 예산', '컴퍼니맨 일정 소개', '컴퍼니맨 팀 소개', '컴퍼니맨 선물 소개', 0, 'N', TO_DATE('2024.01.28','YYYY.MM.DD'), TO_DATE('2024.02.08','YYYY.MM.DD'), TO_DATE('2024.05.19','YYYY.MM.DD'), TO_DATE('2024.05.20','YYYY.MM.DD'), 'N');
INSERT INTO PROJECT(NO, STATUS_NO, CATEGORY_NO, MEMBER_NO, TITLE, GOAL_AMOUNT, IMAGE_URL, TXT_DESCRIPTION, TXT_BUDGET, TXT_SCHEDULE, TXT_TEAM, TXT_ITEM, CURRENT_AMOUNT, OK_YN, ENROLL_DATE, START_DATE, END_DATE, CAL_DATE, DELETE_YN) VALUES (SEQ_PROJECT_NO.NEXTVAL, 1, 11, 10, '숲속 깊은 곳에 위치한 힐링 카페, <카페 포레스트>', 1500000, '카페 포레스트 대표이미지', '카페 포레스트 소개', '카페 포레스트 예산', '카페 포레스트 일정 소개', '카페 포레스트 팀 소개', '카페 포레스트 선물 소개', 0, 'N', TO_DATE('2024.01.29','YYYY.MM.DD'), TO_DATE('2024.03.05','YYYY.MM.DD'), TO_DATE('2024.05.04','YYYY.MM.DD'), TO_DATE('2024.05.05','YYYY.MM.DD'), 'N');
COMMIT;

-- REWARD(선물) 테이블 더미 데이터
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 1, 9900, '[응원 패키지] 후원자 크레딧 + 게임 재화 (만원 상당) + 후원자 트로피 교환권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 1, 24000, '[디지털 패키지] 후원자 크레딧 + 게임 재화 (만원 상당) + 후원자 트로피 교환권 + 과자 성 교환권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 1, 32000, '[컬렉터 패키지] 후원자 크레딧 + 게임 재화 (만원 상당) + 후원자 트로피 교환권 + 천사 차깨비 분양권 + 과자 성 교환권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 2, 9500, '스팀 키 + 크레딧 삽입');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 2, 16000, '스팀 키 + 크레딧 삽입 + 게임 재화(오천원 상당)');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 2, 21000, '스팀 키 + 크레딧 삽입 + 게임 재화(오천원 상당) + 스킨 2종');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 3, 15000, '[부지런한 고양이 에디션] 후원자 Credit + PC 디지털 월페이퍼 + 스팀 키');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 3, 49000, '[응원해요 에디션] 후원자 Credit + PC 디지털 월페이퍼 + 스팀키 + 디지털 아트북');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 3, 75000, '[페르시안 에디션] 후원자 Credit + PC 디지털 월페이퍼 + 스팀키 + 디지털 아트북 + 디지털 OST');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 4, 5500, '광고제거권 : 후원자 크레딧 기재 + 광고 제거권');

INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 4, 10000, '디저털 굿즈 패키지 : 후원자 크레딧 기재 + 광고 제거권 + 디지털 굿즈');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 4, 200000, '요리사 패키지 : 후원자 크레딧 기재 + 광고 제거권 + 디지털 굿즈 + NPC 디자인권 + 음식 디자인권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 5, 3000, '게임파일');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 5, 10000, '게임파일 + 특별 아이템 증정 + 후원자 명예의 전당 등록');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 5, 50000, '게임 파일 + 특별 아이템 증정 + 후원자 명예의 전당 등록 + 인게임 엔딩로 도와주신분 이름 등록');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 6, 9900, '[왕사의 꾸러미] 크레딧 기재 + 디지털 OST 패키지');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 6, 20000, '[여한의 선물] 크레딧 기재 + 디지털 OST 패키지 + 디지털 일러스트');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 7, 14900, '[초보 집사 패키지] 크레딧 추가 + 베타 테스트권 + 후원자 업적');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 7, 23900, '[폴꾸 집사 패키지] 크레딧 추가 + 베타 테스트권 + 후원자 업적 + 모바일 월페이퍼 5종');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 7, 148900, '[전설의 집사 패키지] 크레딧 추가 + 베타 테스트권 + 후원자 업적 + 디지털 BGM 패키지 + 모바일 웹페이피 5종');

INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 8, 14800, '크래딧 + 스팀 키');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 8, 42900, '크래딧 + 스팀 키 + 디지털 OST');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 9, 12000, '크래딧 + 스팀키');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 9, 25100, '크래딧 + 스팀키 + 디지털 OST');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 10, 12000, '[메로페 디지털 패키지] 베타테스트 참여권 + 후원자 명단 기재 + 텀블벅 한정 스킨');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 10, 28000, '[아스테 디럭스 패키지] 베타테스트 참여권 + 텀블벅 한정 스킨 + 음악팩 Iris, Libera');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 10, 58000, '[이리스 OST 패키지] 베타테스트 참여권 + 후원자 명단 기재 + 텀블벅 한정 스킨 + 카파 OST 패키지 + 음악팩 Iris, Libera');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 11, 8800, '스팀키 + 스텝롤');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 11, 11800, '스팀키 + 스텝롤 + 미니 OST');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 11, 19800, '스팀키 + 스텝롤 + 미니 OST + 디지털 월페이퍼');

INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 12, 5000, '후원자명단 기재 + 베타테스트 참여권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 12, 13000, '후원자명단 기재 + 베타테스트 참여권 + 한정스킨');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 13, 10000, '크레딧 추가 + 베타 테스트권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 13, 25000, '크레딧 추가 + 베타 테스트권 + 한정스킨');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 14, 15000, '후원자 한정 업적 + 후원자 한정 환상체 씨앗');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 14, 33000, '후원자 한정 업적 + 후원자 한정 환상체 씨앗 + 라라의 특별 의상');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 14, 66000, '후원자 한정 업적 + 후원자 한정 환상체 씨앗 + 라라의 특별 의상 + 환상체 디자인권');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 15, 5000, '게임파일');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 15, 15000, '게임파일 + 특별 아이템 증정');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 16, 10000, '게임파일 + 디지털 OST 패키지');

INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 16, 25000, '게임파일 + 디지털 OST 패키지 + 디지털 일러스트');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 17, 5000, '엔딩 크레딧 기재');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 17, 10000, '엔딩 크레딧 기재 + 스팀 제품 키');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 17, 50000, '엔딩 크레딧 기재 + 스팀 제품 키 + 원하는 메시지나 이미지 인게임 적용 배치');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 18, 5000, '후원자 명단 기재');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 18, 10000, '후원자 명단 기재 + 인게임 프리미엄 팩 2개');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 18, 20000, '후원자 명단 기재 + 인게임 프리미엄 팩 2개 + 인게임 한정 네임카드');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 19, 5000, '후원자 명단에 기재');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 19, 10000, '후원자 명단에 기재 + 게임 내 유료아이템 증정(오천원 상당)');
INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 20, 5500, '플레이 에디션 - 크레딧 기재 + 광고 제거권');

INSERT INTO REWARD (NO, PROJECT_NO, AMOUNT, NAME) VALUES (SEQ_REWARD_NO.NEXTVAL, 20, 18000, '디지털 다꾸 에디션 - 크레딧 기재 + 광고 제거권 + 디지털 스티커 + 디지털 다이어리 pdf');
COMMIT;

-- PROJECT_UPDATE(업데이트) 테이블 더미 데이터
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 1, '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 업데이트 내용 1', TO_DATE('2023.10.20','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 2, '달 뒤편의 꾸덕한 비밀, 게임 <치즈문> 업데이트 내용 1', TO_DATE('2023.10.29','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 3, '니나노 업데이트 내용1', TO_DATE('2023.10.30','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 5, '트레이시아 내용 1', TO_DATE('2023.11.05','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 4, '새동산 업데이트 내용1', TO_DATE('2023.11.08','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 7, '냥냥섬 업데이트 내용 1', TO_DATE('2023.11.10','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 2, '달 뒤편의 꾸덕한 비밀, 게임 <치즈문> 업데이트 내용 2', TO_DATE('2023.11.13','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 6, '새로운 왕을 위하여 업데이트 내용 1', TO_DATE('2023.11.14','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 1, '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 업데이트 내용 2', TO_DATE('2023.11.15','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 7, '냥냥섬 업데이트 내용 2', TO_DATE('2023.11.18','YYYY.MM.DD'));

INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 3, '니나노 업데이트 내용2', TO_DATE('2023.11.18','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 9, 'Full Metal Furies 업데이트 내용 1', TO_DATE('2023.11.19','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 8, '노배나 업데이트 내용 1', TO_DATE('2023.11.20','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 5, '트레이시아 업데이트 내용 2', TO_DATE('2023.11.23','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 7, '냥냥섬 업데이트 내용 3', TO_DATE('2023.11.24','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 6, '새로운 왕을 위하여 업데이트 내용 2', TO_DATE('2023.12.05','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 10, 'KALPA 업데이트 내용 1', TO_DATE('2023.12.15','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 9, 'Full Metal Furies 업데이트 내용 2', TO_DATE('2023.12.20','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 11, '클루 업데이트 내용 1', TO_DATE('2023.12.30','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 16, 'Princess Maker3 업데이트 내용 1', TO_DATE('2024.01.06','YYYY.MM.DD'));

INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 12, 'URLATE 업데이트 내용 1', TO_DATE('2024.01.30','YYYY.MM.DD'));
INSERT INTO PROJECT_UPDATE(NO, PROJECT_NO, CONTENT, ENROLL_DATE) VALUES (SEQ_PROJECT_UPDATE_NO.NEXTVAL, 14, '별의 여행자 라라 업데이트 내용 1', TO_DATE('2024.01.30','YYYY.MM.DD'));
COMMIT;

-- COMMUNITY(커뮤니티) 테이블 더미 데이터
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 1, 3, '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 커뮤니티 내용1', TO_DATE('2023.10.08','YYYY.MM.DD'), '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 커뮤니티 답변1', TO_DATE('2023.10.10','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 1, 4, '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 커뮤니티 내용2', TO_DATE('2023.10.09','YYYY.MM.DD'), '몽글몽글 도깨비 키우기 게임 <차깨비 찻집> 커뮤니티 답변2', TO_DATE('2023.10.10','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 2, 1, '달 뒤편의 꾸덕한 비밀, 게임 <치즈문> 커뮤니티 내용1 화이팅^^', TO_DATE('2023.10.10','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 3, 2, '니나노 커뮤니티 내용1', TO_DATE('2023.10.20','YYYY.MM.DD'), '니나노 커뮤니티 답변1', TO_DATE('2023.10.21','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 2, 5, '달 뒤편의 꾸덕한 비밀, 게임 <치즈문> 커뮤니티 내용2', TO_DATE('2023.10.23','YYYY.MM.DD'), '달 뒤편의 꾸덕한 비밀, 게임 <치즈문> 커뮤니티 답변2', TO_DATE('2023.10.24','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 4, 3, '새동산 커뮤니티 내용1', TO_DATE('2023.10.29','YYYY.MM.DD'), '새동산 커뮤니티 답변1', TO_DATE('2023.11.05','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 5, 10, '트레이시아 커뮤니티 내용1', TO_DATE('2023.10.29','YYYY.MM.DD'), '트레이시아 커뮤니티 답변1', TO_DATE('2023.10.30','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 3, 7, '니나노 커뮤니티 내용2', TO_DATE('2023.10.30','YYYY.MM.DD'), '니나노 커뮤니티 답변2', TO_DATE('2023.11.02','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 5, 8, '트레이시아 커뮤니티 내용2', TO_DATE('2023.11.08','YYYY.MM.DD'), '트레이시아 커뮤니티 답변2', TO_DATE('2023.11.10','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 4, 7, '새동산 커뮤니티 내용2', TO_DATE('2023.11.26','YYYY.MM.DD'), '새동산 커뮤니티 답변2', TO_DATE('2023.11.29','YYYY.MM.DD'));

INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 8, 9, '노베나 커뮤니티 내용1', TO_DATE('2023.11.27','YYYY.MM.DD'), '노베나 커뮤니티 답변 1', TO_DATE('2023.11.30','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 7, 6, '냥냥섬 커뮤니티 내용 1', TO_DATE('2023.11.28','YYYY.MM.DD'), '냥냥섬 커뮤니티 답변 1', TO_DATE('2023.11.29','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 9, 4, 'Full Metal Furies 커뮤니티 내용1', TO_DATE('2023.11.29','YYYY.MM.DD'), 'Full Metal Furies 커뮤니티 답변 1', TO_DATE('2023.11.30','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 11, 3, '클루 커뮤니티 내용1', TO_DATE('2023.11.30','YYYY.MM.DD'), '클루 커뮤니티 답변 1', TO_DATE('2023.12.02','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 6, 4, '새로운 왕을 위하여 커뮤니티 내용 1', TO_DATE('2023.12.03','YYYY.MM.DD'), '새로운 왕을 위하여 커뮤니티 답변1', TO_DATE('2023.12.04','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 8, 1, '노베나 커뮤니티 내용2', TO_DATE('2023.12.09','YYYY.MM.DD'), '노베나 커뮤니티 답변 2', TO_DATE('2023.12.10','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 15, 2, 'Banished 커뮤니티 내용1', TO_DATE('2023.12.25','YYYY.MM.DD'), 'Banished 커뮤니티 답변 1', TO_DATE('2023.01.01','YYYY.MM.DD'));
INSERT INTO COMMUNITY(NO, PROJECT_NO, MEMBER_NO, CONTENT, CONTENT_ENROLL_DATE, REPLY, REPLY_ENROLL_DATE) VALUES (SEQ_COMMUNITY_NO.NEXTVAL, 14, 9, '별의 여행자 라라 커뮤니티 내용 1', TO_DATE('2024.02.10','YYYY.MM.DD'), '별의 여행자 라라 커뮤니티 답변 1', TO_DATE('2023.02.13','YYYY.MM.DD'));
COMMIT;

-- SETTLEMENT_INFO(정산정보) 테이블 더미 데이터
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 1, '국민은행', '김지민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 2, '신한은행', '이현우', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 3, '우리은행', '박지현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 4, '카카오뱅크', '최성민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 5, '토스은행', '정민지', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 6, '국민은행', '강은영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 7, '기업은행', '김준영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 8, '하나은행', '이소연', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 9, '새마을금고중앙회', '김현아', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 10, 'KEB하나은행', '박동현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 11, 'NH농협은행', '김서현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 12, '대구은행', '이준호', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 13, 'SC제일은행', '조수빈', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 14, '우체국은행', '이태준', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 15, '경남은행', '김은서', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 16, '대신증권', '이세영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 17, '전북은행', '박현진', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 18, '제주은행', '송예지', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 19, '기업은행', '김강민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 20, '기업은행', '곽철현', 123456789012);
commit;

-- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 더미 데이터
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 1, 1, TO_TIMESTAMP('2023-10-03 12:35:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 1, 1, TO_TIMESTAMP('2023-10-04 15:34:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 2, 2, TO_TIMESTAMP('2023-10-05 09:51:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 2, 2, TO_TIMESTAMP('2023-10-08 17:06:21', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 3, 4, TO_TIMESTAMP('2023-10-10 01:55:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 3, 4, TO_TIMESTAMP('2023-10-11 20:36:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 4, 5, TO_TIMESTAMP('2023-10-09 12:35:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 4, 5, TO_TIMESTAMP('2023-10-11 16:05:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 5, 6, TO_TIMESTAMP('2023-10-19 01:27:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 5, 6, TO_TIMESTAMP('2023-10-20 17:24:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 6, 3, TO_TIMESTAMP('2023-10-30 03:32:28', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 6, 3, TO_TIMESTAMP('2023-10-30 07:13:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 7, 8, TO_TIMESTAMP('2023-11-04 13:06:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 7, 8, TO_TIMESTAMP('2023-11-05 19:01:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 8, 7, TO_TIMESTAMP('2023-11-05 21:06:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 8, 7, TO_TIMESTAMP('2023-11-06 22:04:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 9, 9, TO_TIMESTAMP('2023-11-09 22:12:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 9, 9, TO_TIMESTAMP('2023-11-10 10:48:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 10, 10, TO_TIMESTAMP('2023-11-14 12:34:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 10, 10, TO_TIMESTAMP('2023-11-15 20:23:52', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 11, 1, TO_TIMESTAMP('2023-11-19 06:28:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 11, 1, TO_TIMESTAMP('2023-11-21 20:23:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 12, 4, TO_TIMESTAMP('2023-11-25 12:35:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 12, 4, TO_TIMESTAMP('2023-11-26 12:34:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 13, 2, TO_TIMESTAMP('2023-11-29 10:48:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 13, 2, TO_TIMESTAMP('2023-11-29 21:06:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 14, 3, TO_TIMESTAMP('2023-12-08 10:18:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 14, 3, TO_TIMESTAMP('2023-12-09 09:35:07', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 15, 5, TO_TIMESTAMP('2023-12-15 15:45:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 15, 5, TO_TIMESTAMP('2023-12-17 00:31:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 16, 6, TO_TIMESTAMP('2023-12-22 08:41:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 16, 6, TO_TIMESTAMP('2023-12-23 11:09:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 17, 7, TO_TIMESTAMP('2024-01-03 12:35:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 17, 7, TO_TIMESTAMP('2024-01-03 13:27:32', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 18, 8, TO_TIMESTAMP('2024-01-27 20:13:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 18, 8, TO_TIMESTAMP('2024-01-28 23:49:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 19, 9, TO_TIMESTAMP('2024-01-29 10:18:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 19, 9, TO_TIMESTAMP('2024-02-05 17:38:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 20, 10, TO_TIMESTAMP('2024-02-02 04:08:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 20, 10, TO_TIMESTAMP('2024-03-01 21:30:28', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

--  BACKER(후원정보) 테이블 더미 데이터
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 2, 2, TO_TIMESTAMP('2023-11-01 16:05:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 3, 3, TO_TIMESTAMP('2023-11-02 01:27:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 4, 2, TO_TIMESTAMP('2023-11-02 02:05:13', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 5, 1, TO_TIMESTAMP('2023-11-03 13:18:02', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 6, 2, TO_TIMESTAMP('2023-11-03 17:24:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 7, 2, TO_TIMESTAMP('2023-11-04 03:32:28', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 8, 2, TO_TIMESTAMP('2023-11-05 07:13:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 9, 3, TO_TIMESTAMP('2023-11-06 13:06:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 10, 1, TO_TIMESTAMP('2023-11-07 19:01:26', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 2, 2, TO_TIMESTAMP('2023-11-07 21:06:53', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 1, 2, TO_TIMESTAMP('2023-11-07 22:04:44', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 2, 3, TO_TIMESTAMP('2023-11-07 22:12:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 3, 1, TO_TIMESTAMP('2023-11-08 10:48:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 4, 1, TO_TIMESTAMP('2023-11-08 11:04:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 5, 2, TO_TIMESTAMP('2023-11-08 12:34:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 6, 3, TO_TIMESTAMP('2023-11-08 14:52:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 7, 1, TO_TIMESTAMP('2023-11-08 20:23:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 8, 2, TO_TIMESTAMP('2023-11-09 04:44:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 9, 2, TO_TIMESTAMP('2023-11-09 06:28:12', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 10, 3, TO_TIMESTAMP('2023-11-09 11:56:47', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 1, 1, TO_TIMESTAMP('2023-11-09 12:07:05', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 2, 2, TO_TIMESTAMP('2023-11-09 15:45:27', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 3, 3, TO_TIMESTAMP('2023-11-10 00:31:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 4, 1, TO_TIMESTAMP('2023-11-10 08:41:19', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 5, 2, TO_TIMESTAMP('2023-11-10 11:09:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 6, 3, TO_TIMESTAMP('2023-11-10 13:27:32', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 7, 1, TO_TIMESTAMP('2023-11-10 20:13:57', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 8, 2, TO_TIMESTAMP('2023-11-10 23:49:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 9, 2, TO_TIMESTAMP('2023-11-11 10:18:33', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BACKER(NO, PROJECT_NO, MEMBER_NO, REWARD_NO, BACKING_DATE) VALUES(SEQ_BACKER_NO.NEXTVAL, 1, 10, 1, TO_TIMESTAMP('2023-11-11 17:38:19', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

--  REVIEW(후기) 테이블 더미 데이터
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 2, 1, 1, '시간순삭... 도깨비 하나 키우다가 48시간이 훌쩍 지나갔어요. 꿀잼', 5);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 4, 1, 3, '그냥 그래요... 노가다가 너무 심해요', 3);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 10, 1, 9, '생각보다 진짜 재밌는데요? 크게 기대 안했는데', 4);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 1, 2, 11, '마지막에 달 뒷편 비밀 밝혀질 때 나 왜 울어...', 5);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 3, 2, 13, '잘 하다가 중간은 조금 지루....', 2);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 7, 3, 17, '스타듀밸리 같은 게임 찾아다닌지 어언 5년... 드디어 찾았다', 5);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 9, 3, 19, '노가다 너무 심해요. 스팀에서 샀으면 2시간 하기 전에 환불했을 텐데 이건 환불도 못하고', 1);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 1, 4, 21, '시간 때우기 딱 좋아요', 3);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 5, 4, 25, '은근 중독성 있네 이거....', 3);
INSERT INTO REVIEW(NO, MEMBER_NO, PROJECT_NO, BACKER_NO, CONTENT, RATING) VALUES(SEQ_REVIEW_NO.NEXTVAL, 10, 5, 30, '이거 명작이다...... 스토리부터 그래픽까지 뭐 하나 완벽하지 않은 게 없다....', 5);
COMMIT;

--  PAYMENT_STATUS(결제상태) 테이블 더미 데이터
INSERT INTO PAYMENT_STATUS(NO, PAYMENT_STATUS) VALUES(SEQ_PAYMENT_STATUS_NO.NEXTVAL, '결제완료');
INSERT INTO PAYMENT_STATUS(NO, PAYMENT_STATUS) VALUES(SEQ_PAYMENT_STATUS_NO.NEXTVAL, '결제실패');
COMMIT;

--  PAYMENT_TYPE(결제수단) 테이블 더미 데이터
INSERT INTO PAYMENT_TYPE(NO, PAYMENT_TYPE) VALUES(SEQ_PAYMENT_TYPE_NO.NEXTVAL, '카드');
INSERT INTO PAYMENT_TYPE(NO, PAYMENT_TYPE) VALUES(SEQ_PAYMENT_TYPE_NO.NEXTVAL, '카카오페이');
COMMIT;

--  PAYMENT(결제정보) 테이블 더미 데이터
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 1, 1, 1, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 24000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 2, 1, 2, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 32000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 3, 1, 1, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 24000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 4, 1, 2, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 9900);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 5, 1, 1, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 24000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 6, 1, 2, 2, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 24000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 7, 1, 1, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 24000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 8, 1, 2, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 32000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 9, 1, 1, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 9900);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 11, 1, 2, 2, TO_TIMESTAMP('2023-11-24', 'YYYY-MM-DD HH24:MI:SS'), 16000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 12, 2, 1, 1, TO_TIMESTAMP('2023-11-24', 'YYYY-MM-DD HH24:MI:SS'), 21000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 13, 2, 2, 1, TO_TIMESTAMP('2023-11-24', 'YYYY-MM-DD HH24:MI:SS'), 9500);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 14, 2, 1, 1, TO_TIMESTAMP('2023-11-24', 'YYYY-MM-DD HH24:MI:SS'), 9500);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 15, 2, 2, 1, TO_TIMESTAMP('2023-11-24', 'YYYY-MM-DD HH24:MI:SS'), 49000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 16, 3, 1, 1, TO_TIMESTAMP('2023-11-20', 'YYYY-MM-DD HH24:MI:SS'), 75000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 17, 3, 2, 1, TO_TIMESTAMP('2023-11-20', 'YYYY-MM-DD HH24:MI:SS'), 15000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 18, 3, 1, 1, TO_TIMESTAMP('2023-11-20', 'YYYY-MM-DD HH24:MI:SS'), 49000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 19, 3, 2, 1, TO_TIMESTAMP('2023-11-20', 'YYYY-MM-DD HH24:MI:SS'), 49000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 20, 3, 1, 1, TO_TIMESTAMP('2023-11-20', 'YYYY-MM-DD HH24:MI:SS'), 5500);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 22, 4, 2, 1, TO_TIMESTAMP('2023-12-01', 'YYYY-MM-DD HH24:MI:SS'), 10000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 23, 4, 1, 1, TO_TIMESTAMP('2023-12-01', 'YYYY-MM-DD HH24:MI:SS'), 200000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 24, 4, 2, 1, TO_TIMESTAMP('2023-12-01', 'YYYY-MM-DD HH24:MI:SS'), 3000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 25, 4, 1, 1, TO_TIMESTAMP('2023-12-01', 'YYYY-MM-DD HH24:MI:SS'), 10000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 26, 5, 2, 1, TO_TIMESTAMP('2023-11-30', 'YYYY-MM-DD HH24:MI:SS'), 50000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 27, 5, 1, 1, TO_TIMESTAMP('2023-11-30', 'YYYY-MM-DD HH24:MI:SS'), 3000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 28, 5, 2, 1, TO_TIMESTAMP('2023-11-30', 'YYYY-MM-DD HH24:MI:SS'), 10000);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 29, 5, 1, 1, TO_TIMESTAMP('2023-11-30', 'YYYY-MM-DD HH24:MI:SS'), 25100);
INSERT INTO PAYMENT(NO, BACKER_NO, PROJECT_NO, PAYMENT_TYPE_NO, PAYMENT_STATUS_NO, PAYMENT_DATE, AMOUNT) VALUES(SEQ_PAYMENT_NO.NEXTVAL, 30, 5, 2, 1, TO_TIMESTAMP('2023-12-04', 'YYYY-MM-DD HH24:MI:SS'), 12000);
COMMIT;


