--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 시퀀스
--------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP SEQUENCE SEQ_MEMBER_NO; -- MEMBER 회원
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE; -- MEMBER 회원
DROP SEQUENCE SEQ_CATEGORY_NO; -- CATEGORY 카테고리
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE; -- CATEGORY 카테고리
DROP SEQUENCE SEQ_AD_MEMBER_NO; -- AD_MEMBER 관리자
CREATE SEQUENCE SEQ_AD_MEMBER_NO NOCACHE NOCYCLE; -- AD_MEMBER 관리자
DROP SEQUENCE SEQ_SETTLEMENT_INFO_NO; -- SETTLEMENT_INFO 정산정보
CREATE SEQUENCE SEQ_SETTLEMENT_INFO_NO NOCACHE NOCYCLE; -- SETTLEMENT_INFO 정산정보
DROP SEQUENCE SEQ_PROJECT_EDIT_HISTORY_NO; -- PROJECT_EDIT_HISTORY 프로젝트 수정 이력
CREATE SEQUENCE SEQ_PROJECT_EDIT_HISTORY_NO NOCACHE NOCYCLE; -- PROJECT_EDIT_HISTORY 프로젝트 수정 이력

DROP SEQUENCE SEQ_PAYMENT_NO; -- PAYMENT 결제정보
CREATE SEQUENCE SEQ_PAYMENT_NO NOCACHE NOCYCLE; -- PAYMENT 결제정보
DROP SEQUENCE SEQ_PAYMENT_TYPE_NO; -- PAYMENT_TYPE 결제수단
CREATE SEQUENCE SEQ_PAYMENT_TYPE_NO NOCACHE NOCYCLE; -- PAYMENT_TYPE 결제수단
DROP SEQUENCE SEQ_PAYMENT_STATUS_NO; -- PAYMENT_STATUS 결제상태
CREATE SEQUENCE SEQ_PAYMENT_STATUS_NO NOCACHE NOCYCLE; -- PAYMENT_STATUS 결제상태
DROP SEQUENCE SEQ_REVIEW_NO; -- REVIEW 후기
CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE NOCYCLE; -- REVIEW 후기
DROP SEQUENCE SEQ_BACKER_NO; -- BACKER 후원정보
CREATE SEQUENCE SEQ_BACKER_NO NOCACHE NOCYCLE; -- BACKER 후원정보

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 테이블
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- MEMBER(회원) 테이블
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
	NO	                NUMBER	            PRIMARY KEY
	, NAME	            VARCHAR2(42)	    NOT NULL
	, EMAIL	            VARCHAR2(150)	    NOT NULL        UNIQUE
	, PWD	            VARCHAR2(50)	    NOT NULL
	, PIC	            VARCHAR2(500)	    NULL
	, INTRO	            VARCHAR2(2500)	    NULL
	, SITE_URL	        VARCHAR2(500)	    NULL
	, ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE
	, UPDATE_DATE	    TIMESTAMP	        NULL
	, QUIT_YN	        CHAR(1)	            DEFAULT 'N' CHECK( QUIT_YN IN ('Y','N') )
);
COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.NAME IS '회원 이름 기본/변경가능';
COMMENT ON COLUMN MEMBER.EMAIL IS '회원 이메일(아이디)';
COMMENT ON COLUMN MEMBER.PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.PIC IS '회원 프로필사진';
COMMENT ON COLUMN MEMBER.INTRO IS '회원 소개';
COMMENT ON COLUMN MEMBER.SITE_URL IS '회원 웹사이트';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일자';
COMMENT ON COLUMN MEMBER.UPDATE_DATE IS '회원 정보 수정일자';
COMMENT ON COLUMN MEMBER.QUIT_YN IS '회원 탈퇴 여부';

-- CATEGORY(카테고리) 테이블
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY (
	NO	                    NUMBER		        NOT NULL
	, MAIN_CATEGORY_NO	    NUMBER		        NOT NULL
	, SUB_CATEGORY_NO	    NUMBER		        NOT NULL
	, MAIN_CATEGORY	        VARCHAR2(100)		NOT NULL
	, SUB_CATEGORY	        VARCHAR2(100)		NOT NULL
);
COMMENT ON COLUMN CATEGORY.NO IS '카테고리 번호';
COMMENT ON COLUMN CATEGORY.MAIN_CATEGORY_NO IS '대분류 번호';
COMMENT ON COLUMN CATEGORY.SUB_CATEGORY_NO IS '소분류 번호';
COMMENT ON COLUMN CATEGORY.MAIN_CATEGORY IS '대분류 이름';
COMMENT ON COLUMN CATEGORY.SUB_CATEGORY IS '소분류 이름';

-- AD_MEMBER(관리자) 테이블
DROP TABLE AD_MEMBER CASCADE CONSTRAINTS;
CREATE TABLE AD_MEMBER (
	NO	                NUMBER		        NOT NULL
	, ID	            VARCHAR2(60)		NOT NULL
	, NAME	            VARCHAR2(42)		NOT NULL
	, PWD	            VARCHAR2(30)		NOT NULL
	, PIC	            VARCHAR2(500)		NULL
	, ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE	NOT NULL
	, QUIT_YN	        CHAR(1)	            DEFAULT 'N'	CHECK( QUIT_YN IN ('Y','N') )
);

COMMENT ON COLUMN AD_MEMBER.NO IS '관리자 번호';
COMMENT ON COLUMN AD_MEMBER.ID IS '관리자 계정 아이디';
COMMENT ON COLUMN AD_MEMBER.NAME IS '관리자 이름';
COMMENT ON COLUMN AD_MEMBER.PWD IS '관리자 비밀번호';
COMMENT ON COLUMN AD_MEMBER.PIC IS '관리자 프로필사진';
COMMENT ON COLUMN AD_MEMBER.ENROLL_DATE IS '계정생성일자';
COMMENT ON COLUMN AD_MEMBER.QUIT_YN IS '계정 활성화 여부';

-- SETTLEMENT_INFO(정산정보) 테이블 외래키있음
DROP TABLE SETTLEMENT_INFO CASCADE CONSTRAINTS;
CREATE TABLE SETTLEMENT_INFO (
	NO	                NUMBER		        NOT NULL
	, PROJECT_NO	    NUMBER		        NOT NULL
	, BANK_NAME	        VARCHAR2(50)		NULL
	, NAME	            VARCHAR2(50)		NULL
	, ACCOUNT_NUM	    NUMBER		        NULL
);
COMMENT ON COLUMN SETTLEMENT_INFO.NO IS '정산정보 번호';
COMMENT ON COLUMN SETTLEMENT_INFO.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN SETTLEMENT_INFO.BANK_NAME IS '거래은행 이름';
COMMENT ON COLUMN SETTLEMENT_INFO.NAME IS '예금주명';
COMMENT ON COLUMN SETTLEMENT_INFO.ACCOUNT_NUM IS '계좌번호';

-- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블
DROP TABLE PROJECT_EDIT_HISTORY CASCADE CONSTRAINTS;
CREATE TABLE PROJECT_EDIT_HISTORY (
	NO	                NUMBER          NOT NULL
	, PROJECT_NO	    NUMBER		    NOT NULL
	, MEMBER_NO     	NUMBER		    NOT NULL
	, MODIFY_DATE	    TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN PROJECT_EDIT_HISTORY.NO IS '수정이력 번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN PROJECT_EDIT_HISTORY.MODIFY_DATE IS '프로젝트 수정 이력';

-- REVIEW(후기) 테이블
DROP TABLE REVIEW CASCADE CONSTRAINTS;
CREATE TABLE REVIEW(
    NO                  NUMBER              NOT NULL
    , MEMBER_NO         NUMBER              NOT NULL
    , PROJECT_NO        NUMBER              NOT NULL
    , BACKER_NO         NUMBER              NOT NULL
    , CONTENT           VARCHAR2(4000)      NOT NULL
    , IMAGE             VARCHAR2(4000)      NULL
    , RATING            NUMBER              NOT NULL
);
COMMENT ON COLUMN REVIEW.NO IS '후기 번호';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN REVIEW.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN REVIEW.BACKER_NO IS '후원 번호';
COMMENT ON COLUMN REVIEW.CONTENT IS '후기 내용';
COMMENT ON COLUMN REVIEW.IMAGE IS '후기 이미지';
COMMENT ON COLUMN REVIEW.RATING IS '후기 별점';

-- BACKER(후원정보) 테이블
DROP TABLE BACKER CASCADE CONSTRAINTS;
CREATE TABLE BACKER(
    NO                  NUMBER          NOT NULL
    , PROJECT_NO        NUMBER          NOT NULL
    , MEMBER_NO         NUMBER          NOT NULL
    , REWARD_NO         NUMBER          NOT NULL
    , BACKING_DATE      TIMESTAMP       DEFAULT SYSDATE NOT NULL
    , RETRACT_YN        CHAR(1)         DEFAULT 'N' NOT NULL
);
COMMENT ON COLUMN BACKER.NO IS '후원자 번호';
COMMENT ON COLUMN BACKER.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN BACKER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN BACKER.REWARD_NO IS '선물 번호';
COMMENT ON COLUMN BACKER.BACKING_DATE IS '후원일자';
COMMENT ON COLUMN BACKER.RETRACT_YN IS '후원취소 여부';

-- PAYMENT_STATUS(결제상태) 테이블
DROP TABLE PAYMENT_STATUS CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_STATUS (
    NO                  NUMBER          NOT NULL
    , PAYMENT_STATUS    VARCHAR2(20)    NOT NULL
);
COMMENT ON COLUMN PAYMENT_STATUS.NO IS '결제상태 번호';
COMMENT ON COLUMN PAYMENT_STATUS.PAYMENT_STATUS IS '결제상태';

-- PAYMENT_TYPE(결제수단) 테이블
DROP TABLE PAYMENT_TYPE CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT_TYPE (
    NO                  NUMBER          NOT NULL
    , PAYMENT_TYPE      VARCHAR2(100)   NOT NULL
);
COMMENT ON COLUMN PAYMENT_TYPE.NO IS '결제수단 번호';
COMMENT ON COLUMN PAYMENT_TYPE.PAYMENT_TYPE IS '결제수단';

-- PAYMENT(결제정보) 테이블
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
CREATE TABLE PAYMENT (
    NO                      NUMBER          NOT NULL
    , BACKER_NO             NUMBER          NOT NULL
    , PROJECT_NO            NUMBER          NOT NULL
    , PAYMENT_TYPE_NO       NUMBER          NOT NULL
    , PAYMENT_STATUS_NO     NUMBER          NOT NULL
    , PAYMENT_DATE          TIMESTAMP       NOT NULL
    , AMOUNT                NUMBER          NOT NULL
);
COMMENT ON COLUMN PAYMENT.NO IS '결제정보 번호';
COMMENT ON COLUMN PAYMENT.BACKER_NO IS '후원자 번호';
COMMENT ON COLUMN PAYMENT.PROJECT_NO IS '프로젝트 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_TYPE_NO IS '결제수단 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_STATUS_NO IS '결제상태 번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '결제 일자';
COMMENT ON COLUMN PAYMENT.AMOUNT IS '결제 금액';

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 외래키
--------------------------------------------------------------------------------------------------------------------------------------------------------------
--ALTER TABLE SETTLEMENT_INFO ADD CONSTRAINT PROJECT_NO FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- SETTLEMENT_INFO(정산정보) 테이블 외래키
--ALTER TABLE PROJECT_EDIT_HISTORY ADD CONSTRAINT PROJECT_NO FOREIGN KEY(PROJECT_NO) REFERENCES PROJECT(NO); -- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 외래키
--ALTER TABLE PROJECT_EDIT_HISTORY ADD CONSTRAINT MEMBER_NO FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(NO); -- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 외래키

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 더미데이터
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- MEMBER(회원) 테이블 더미 데이터
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '현지연', 'clsrnclsrn1111@naver.com', '1234', 'image.jpg', '향수 애호가를 위한 프래그런스 브랜드. 세이리.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '한윤지', 'gksdbswl@gmail.com', '1234', 'image.jpg', '창작자분들을 위한 유니크한 자료를 만듭니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '이경민', 'dlrudals@naver.com', '1234', 'image.jpg', '<지난 펀딩 소재 스토어 - 오픈중>', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '판타지문학사', 'fantasy@naver.com', '1234', 'image.jpg', '판타지 세계의 모든 것들을 다루고 있습니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, 'TextPlanet', 'textplanet@gmail.com', '1234', 'image.jpg', 'TextPlanet(텍스트플래닛)은 창작자를 위한 새로운 세계를 언어를 통해 창조하는 언어학 창작 그룹입니다. 높은 완성도로 여러분께 만족감을 드리겠습니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '나랑하', 'narangha@naver.com', '1234', 'image.jpg', '우리 주변의 다양한 이야기를 소개하는 출판 전문 스튜디오, 스튜디오 나랑하입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '나래꿈', 'nareggoum@naver.com', '1234', 'image.jpg', '트위터 : @naredream 인스타 : naredream', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '하이꽈베트남어', 'betnam@gmail.com', '1234', 'image.jpg', '<도전! 베트남 요리왕>을 통해 다 함께 베트남의 매력 속에 빠져 보세요!', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '위콘 게임즈 (WeCon Games)', 'wecon@naver.com', '1234', 'image.jpg', '안녕하세요! 보드게임 작가 도지 입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
INSERT INTO MEMBER (NO, NAME, EMAIL, PWD, PIC, INTRO, SITE_URL, ENROLL_DATE, UPDATE_DATE, QUIT_YN)
VALUES (SEQ_MEMBER_NO.NEXTVAL, '야생의 멧씨', 'metcy@naver.com', '1234', 'image.jpg', '솔직한 즐거움으로 보드게임을 만들고 있는 멧씨입니다.', 'http://www.example.com/john', SYSDATE, NULL, 'N');
commit;

-- AD_MEMBER(관리자) 테이블 더미 데이터
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin1', '관리자1', '1234', 'admin_pic1.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin2', '관리자2', '1234', 'admin_pic2.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin3', '관리자3', '1234', 'admin_pic3.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin4', '관리자4', '1234', 'admin_pic4.jpg', SYSDATE, 'N');
INSERT INTO AD_MEMBER (NO, ID, NAME, PWD, PIC, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_AD_MEMBER_NO.NEXTVAL, 'admin5', '관리자5', '1234', 'admin_pic5.jpg', SYSDATE, 'N');
commit;

-- CATEGORY(카테고리) 테이블 더미 데이터
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 1, '비디오게임', 'RPG');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 2, '비디오게임', '시뮬레이션');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 3, '비디오게임', '생존');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 4, '비디오게임', '추리·공포');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 5, '비디오게임', '리듬');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 1, 6, '비디오게임', '기타');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 1, '모바일게임', '퍼즐');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 2, '모바일게임', '슈팅');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 3, '모바일게임', '시뮬레이션');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 4, '모바일게임', '어드벤처');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 5, '모바일게임', '타이쿤');
INSERT INTO CATEGORY (NO, MAIN_CATEGORY_NO, SUB_CATEGORY_NO, MAIN_CATEGORY, SUB_CATEGORY)
VALUES (SEQ_CATEGORY_NO.NEXTVAL, 2, 6, '모바일게임', '기타');

-- SETTLEMENT_INFO(정산정보) 테이블 더미 데이터
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 1, '국민은행', '김지민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 2, '신한은행', '이현우', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 3, '우리은행', '박지현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 4, '카카오뱅크', '최성민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 5, '토스은행', '정민지', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 6, '국민은행', '강은영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 7, '기업은행', '김준영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 8, '하나은행', '이소연', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 9, '새마을금고중앙회', '김현아', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 10, 'KEB하나은행', '박동현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 11, 'NH농협은행', '김서현', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 12, '대구은행', '이준호', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 13, 'SC제일은행', '조수빈', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 14, '우체국은행', '이태준', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 15, '경남은행', '김은서', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 16, '대신증권', '이세영', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 17, '전북은행', '박현진', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 18, '제주은행', '송예지', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 19, '기업은행', '김강민', 123456789012);
INSERT INTO SETTLEMENT_INFO (NO, PROJECT_NO, BANK_NAME, NAME, ACCOUNT_NUM)
VALUES (SEQ_SETTLEMENT_INFO_NO.NEXTVAL, 20, '기업은행', '곽철현', 123456789012);
commit;

-- PROJECT_EDIT_HISTORY(프로젝트 수정 이력) 테이블 더미 데이터 1227 프로젝트 테이블 보고 만들어야함
--INSERT INTO PROJECT_EDIT_HISTORY (NO, PROJECT_NO, MEMBER_NO, MODIFY_DATE)
--VALUES (SEQ_PROJECT_EDIT_HISTORY_NO.NEXTVAL, 1, 101, SYSTIMESTAMP);


---------------------------------------------------------------------------------












